export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL";
export const FETCH_TODOS_START = "FETCH_TODOS_START";

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";
export const DELETE_TODO_START = "DELETE_TODO_START";

export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_FAIL = "TOGGLE_TODO_FAIL";
export const TOGGLE_TODO_START = "TOGGLE_TODO_START";

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAIL = "ADD_TODO_FAIL";
export const ADD_TODO_START = "ADD_TODO_START";

export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";
export const UPDATE_TODO_START = "UPDATE_TODO_START";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
